CREATE OR REPLACE FUNCTION max_hours (
    p_lecturer_id_start IN LECTURER.LECTURER_ID%TYPE,
    p_lecturer_id_end IN LECTURER.LECTURER_ID%TYPE,
    p_subject_name IN SUBJECT.SUBJ_NAME%TYPE
) RETURN INTEGER AS

  v_max_hours INTEGER;
  
BEGIN

  SELECT MAX(SUBJECT.HOUR)
  INTO v_max_hours
  FROM SUBJECT 
  INNER JOIN SUBJ_LECT ON SUBJECT.SUBJ_ID = SUBJ_LECT.SUBJ_ID
  INNER JOIN LECTURER ON SUBJ_LECT.LECTURER_ID = LECTURER.LECTURER_ID
  WHERE LECTURER.LECTURER_ID BETWEEN p_lecturer_id_start AND p_lecturer_id_end
  AND SUBJECT.SUBJ_NAME = p_subject_name;

  RETURN v_max_hours;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;

END max_hours;
/
