
CREATE OR REPLACE PACKAGE BODY PKG AS 

  FUNCTION COUNT_SUBJECTS RETURN INTEGER IS 
    SUBJECT_COUNT INTEGER;
  BEGIN
    SELECT COUNT(DISTINCT SUBJ_ID) INTO SUBJECT_COUNT
    FROM EXAMS 
    WHERE MARK > (SELECT AVG(MARK) 
                  FROM EXAMS 
                  GROUP BY SUBJ_ID
                  HAVING COUNT(STUD_ID) > 10);

    -- Здесь встроен вызов процедуры
    TRACK_FUNCTION_USAGE;

    RETURN SUBJECT_COUNT;
  END COUNT_SUBJECTS;

  PROCEDURE TRACK_FUNCTION_USAGE IS 
    AVG_MARK FLOAT;
    SUBJECT_COUNT INTEGER;
  BEGIN
    SELECT AVG(MARK), COUNT(DISTINCT SUBJ_ID) INTO AVG_MARK, SUBJECT_COUNT
    FROM EXAMS
    WHERE MARK > (SELECT AVG(MARK) 
                  FROM EXAMS 
                  GROUP BY SUBJ_ID
                  HAVING COUNT(STUD_ID) > 10);

    INSERT INTO TRACK_FUNCTION (AVG_MARK, SUBJECT_COUNT)
    VALUES (AVG_MARK, SUBJECT_COUNT);

    COMMIT;
  END TRACK_FUNCTION_USAGE;
END PKG;
/
