DROP TABLE STUDENT_LAB_5;
DROP TRIGGER STUDENT_LAB_5_INS;
DROP SEQUENCE STUDENT_LAB_5_SEQ;

CREATE TABLE STUDENT_LAB_5 (
  ID INTEGER PRIMARY KEY,
  NAME CHAR(200) NOT NULL
);

CREATE SEQUENCE STUDENT_LAB_5_SEQ
 START WITH     1
 INCREMENT BY   1;

CREATE OR REPLACE TRIGGER STUDENT_LAB_5_INS
BEFORE INSERT ON STUDENT_LAB_5
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT STUDENT_LAB_5_SEQ.NEXTVAL INTO :NEW.id FROM dual;
  END IF;
END;
/
